<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Message_message-text</name>
   <tag></tag>
   <elementGuidId>a609a49f-ed79-4fcc-8d03-2d7ab92d72ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#message-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='message-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>bc223c15-af72-4548-a04c-db445210edf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4e46d82a-95a8-4503-83ed-f1f3ee4d16d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>message-text</value>
      <webElementGuid>9215e6fa-8cee-4786-aecb-02b141b256e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;message-text&quot;)</value>
      <webElementGuid>7025e410-6f8f-4450-ab93-337e5152ac44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='message-text']</value>
      <webElementGuid>2b59fb3d-fbb9-48dc-a070-b934f2756a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='exampleModal']/div/div/div[2]/form/div[3]/textarea</value>
      <webElementGuid>7269aea8-7cea-4e6b-adca-a090d018df9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>1428fb72-61bb-4784-b3c4-cb13732a6498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'message-text']</value>
      <webElementGuid>c6d199bd-6093-4239-a441-d6c20a5ee6f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
